# basic options (hash = comment)
title: Dr Luke Barrett
author: Luke T Barrett
email: barrett.luke@gmail.com
description: Dr Luke T Barrett | Research on marine ecology, fish biology, and aquaculture environment interactions
twitter_username: LukeBarrettSci
github_username:  neoodax

# Build settings
markdown: kramdown
theme: minima

# customise navigation
header_pages:
  - index.md
#  - blog/index.md
  - publications.md
  - media.md
  - contact.md
